// Generated by Scripts/update_hugeicons.py. Do not edit.
import Foundation

public struct HugeIcon: Hashable, Sendable, Identifiable {
    public let name: String
    public let scalar: UInt32

    public var id: String { name }

    public var character: String {
        UnicodeScalar(scalar).map(String.init) ?? ""
    }

    private init(name: String, scalar: UInt32) {
        self.name = name
        self.scalar = scalar
    }

    public static let fontFamily = "hugeicons-stroke-rounded"

    public static let alarmFill = HugeIcon(name: "alarm-clock", scalar: 0xF157B)
    public static let appleLogo = HugeIcon(name: "apple", scalar: 0xF15D9)
    public static let arrowClockwise = HugeIcon(name: "arrow-reload-horizontal", scalar: 0xF1621)
    public static let arrowCounterclockwise = HugeIcon(name: "undo-02", scalar: 0xF28E6)
    public static let arrowDown = HugeIcon(name: "arrow-down-01", scalar: 0xF15FC)
    public static let arrowLeft = HugeIcon(name: "arrow-left-01", scalar: 0xF1612)
    public static let arrowLeftArrowRight = HugeIcon(name: "arrow-left-right", scalar: 0xF161A)
    public static let arrowRight = HugeIcon(name: "arrow-right-01", scalar: 0xF1623)
    public static let arrowTriangle2Circlepath = HugeIcon(name: "reload", scalar: 0xF2455)
    public static let arrowTurnDownRight = HugeIcon(name: "arrow-turn-down", scalar: 0xF162F)
    public static let arrowUp = HugeIcon(name: "arrow-up-01", scalar: 0xF1632)
    public static let arrowUpArrowDown = HugeIcon(name: "arrow-up-down", scalar: 0xF1639)
    public static let arrowUpForwardApp = HugeIcon(name: "share-08", scalar: 0xF259D)
    public static let arrowUpRight = HugeIcon(name: "arrow-up-right-01", scalar: 0xF1640)
    public static let barcode = HugeIcon(name: "bar-code-01", scalar: 0xF16BF)
    public static let barcodeViewfinder = HugeIcon(name: "barcode-scan", scalar: 0xF16C1)
    public static let bell = HugeIcon(name: "notification-02", scalar: 0xF2230)
    public static let bellBadgeFill = HugeIcon(name: "notification-03", scalar: 0xF2231)
    public static let bellFill = HugeIcon(name: "notification-02", scalar: 0xF2230)
    public static let bolt = HugeIcon(name: "flash", scalar: 0xF1CE8)
    public static let boltFill = HugeIcon(name: "flash", scalar: 0xF1CE8)
    public static let bookClosed = HugeIcon(name: "book-02", scalar: 0xF175C)
    public static let bookClosedFill = HugeIcon(name: "book-02", scalar: 0xF175C)
    public static let bookFill = HugeIcon(name: "book-02", scalar: 0xF175C)
    public static let bookmark = HugeIcon(name: "bookmark-01", scalar: 0xF1778)
    public static let bookmarkFill = HugeIcon(name: "bookmark-01", scalar: 0xF1778)
    public static let booksVertical = HugeIcon(name: "books-01", scalar: 0xF1787)
    public static let cabinet = HugeIcon(name: "cabinet-02", scalar: 0xF1845)
    public static let calendar = HugeIcon(name: "calendar-03", scalar: 0xF1853)
    public static let calendarBadgeMinus = HugeIcon(name: "calendar-minus-01", scalar: 0xF1868)
    public static let calendarBadgePlus = HugeIcon(name: "calendar-add-01", scalar: 0xF1856)
    public static let camera = HugeIcon(name: "camera-01", scalar: 0xF18A4)
    public static let cameraFill = HugeIcon(name: "camera-01", scalar: 0xF18A4)
    public static let cameraViewfinder = HugeIcon(name: "scan-image", scalar: 0xF2528)
    public static let carrot = HugeIcon(name: "carrot", scalar: 0xF18E5)
    public static let cart = HugeIcon(name: "shopping-cart-01", scalar: 0xF25DB)
    public static let cartBadgePlus = HugeIcon(name: "shopping-cart-add-01", scalar: 0xF25DD)
    public static let cartFill = HugeIcon(name: "shopping-cart-01", scalar: 0xF25DB)
    public static let characterBubble = HugeIcon(name: "bubble-chat-translate", scalar: 0xF17DE)
    public static let chartBar = HugeIcon(name: "chart-column", scalar: 0xF191E)
    public static let checklistChecked = HugeIcon(name: "check-list", scalar: 0xF1967)
    public static let checklistUnchecked = HugeIcon(name: "check-list", scalar: 0xF1967)
    public static let checkmark = HugeIcon(name: "tick-01", scalar: 0xF282B)
    public static let checkmarkCircle = HugeIcon(name: "checkmark-circle-02", scalar: 0xF1971)
    public static let checkmarkCircleFill = HugeIcon(name: "checkmark-circle-02", scalar: 0xF1971)
    public static let checkmarkSealFill = HugeIcon(name: "validation-approval", scalar: 0xF2954)
    public static let checkmarkSquare = HugeIcon(name: "checkmark-square-02", scalar: 0xF1975)
    public static let checkmarkSquareFill = HugeIcon(name: "checkmark-square-02", scalar: 0xF1975)
    public static let chevronDown = HugeIcon(name: "arrow-down-01", scalar: 0xF15FC)
    public static let chevronLeft = HugeIcon(name: "arrow-left-01", scalar: 0xF1612)
    public static let chevronRight = HugeIcon(name: "arrow-right-01", scalar: 0xF1623)
    public static let chevronUpChevronDown = HugeIcon(name: "arrow-up-down", scalar: 0xF1639)
    public static let circle = HugeIcon(name: "circle", scalar: 0xF19D1)
    public static let circleDashed = HugeIcon(name: "dashed-line-circle", scalar: 0xF1B1E)
    public static let clock = HugeIcon(name: "clock-01", scalar: 0xF19E3)
    public static let clockArrowCirclepath = HugeIcon(name: "clock-arrow-up", scalar: 0xF19EB)
    public static let creditcard = HugeIcon(name: "credit-card", scalar: 0xF1AA2)
    public static let creditcardFill = HugeIcon(name: "credit-card", scalar: 0xF1AA2)
    public static let cursorarrowClick2 = HugeIcon(name: "cursor-pointer-02", scalar: 0xF1ACF)
    public static let deleteBackward = HugeIcon(name: "delete-put-back", scalar: 0xF1B39)
    public static let dialMedium = HugeIcon(name: "dashboard-speed-01", scalar: 0xF1B13)
    public static let docOnClipboard = HugeIcon(name: "clipboard", scalar: 0xF19E2)
    public static let docOnDoc = HugeIcon(name: "copy-01", scalar: 0xF1A75)
    public static let docText = HugeIcon(name: "document-attachment", scalar: 0xF1BA1)
    public static let dollarsignCircle = HugeIcon(name: "dollar-circle", scalar: 0xF1BA6)
    public static let ellipsis = HugeIcon(name: "more-horizontal", scalar: 0xF218F)
    public static let ellipsisCircle = HugeIcon(name: "menu-circle", scalar: 0xF20E4)
    public static let envelope = HugeIcon(name: "mail-01", scalar: 0xF205C)
    public static let envelopeFill = HugeIcon(name: "mail-01", scalar: 0xF205C)
    public static let exclamationmark = HugeIcon(name: "alert-02", scalar: 0xF1583)
    public static let exclamationmarkBubble = HugeIcon(name: "bubble-chat-notification", scalar: 0xF17D5)
    public static let exclamationmarkTriangleFill = HugeIcon(name: "alert-02", scalar: 0xF1583)
    public static let flame = HugeIcon(name: "fire", scalar: 0xF1CD5)
    public static let flameFill = HugeIcon(name: "fire", scalar: 0xF1CD5)
    public static let flashlightOffFill = HugeIcon(name: "flash-off", scalar: 0xF1CE7)
    public static let flashlightOnFill = HugeIcon(name: "flashlight", scalar: 0xF1CE9)
    public static let folderBadgePlus = HugeIcon(name: "folder-add", scalar: 0xF1D04)
    public static let forkKnife = HugeIcon(name: "spoon-and-fork", scalar: 0xF2678)
    public static let gearshape = HugeIcon(name: "settings-01", scalar: 0xF257F)
    public static let gearshape2 = HugeIcon(name: "settings-02", scalar: 0xF2580)
    public static let globe = HugeIcon(name: "globe", scalar: 0xF1D82)
    public static let heart = HugeIcon(name: "favourite", scalar: 0xF1C60)
    public static let heartFill = HugeIcon(name: "favourite", scalar: 0xF1C60)
    public static let house = HugeIcon(name: "home-03", scalar: 0xF1E33)
    public static let infoCircle = HugeIcon(name: "information-circle", scalar: 0xF1EB4)
    public static let infoCircleFill = HugeIcon(name: "information-circle", scalar: 0xF1EB4)
    public static let internaldrive = HugeIcon(name: "hard-drive", scalar: 0xF1DF6)
    public static let key = HugeIcon(name: "key-01", scalar: 0xF1EFF)
    public static let line3Horizontal = HugeIcon(name: "menu-01", scalar: 0xF20D9)
    public static let line3HorizontalDecrease = HugeIcon(name: "filter-horizontal", scalar: 0xF1CBD)
    public static let line3HorizontalDecreaseCircle = HugeIcon(name: "filter-horizontal", scalar: 0xF1CBD)
    public static let link = HugeIcon(name: "link-01", scalar: 0xF1FA5)
    public static let listBullet = HugeIcon(name: "left-to-right-list-bullet", scalar: 0xF1F86)
    public static let listNumber = HugeIcon(name: "left-to-right-list-number", scalar: 0xF1F88)
    public static let lock = HugeIcon(name: "lock", scalar: 0xF1FEF)
    public static let lockFill = HugeIcon(name: "lock", scalar: 0xF1FEF)
    public static let magnifyingglass = HugeIcon(name: "search-01", scalar: 0xF2546)
    public static let mic = HugeIcon(name: "mic-01", scalar: 0xF211C)
    public static let micFill = HugeIcon(name: "mic-01", scalar: 0xF211C)
    public static let minus = HugeIcon(name: "minus-sign", scalar: 0xF2139)
    public static let paintpalette = HugeIcon(name: "paint-board", scalar: 0xF22A4)
    public static let paintpaletteFill = HugeIcon(name: "paint-board", scalar: 0xF22A4)
    public static let paperplane = HugeIcon(name: "sent", scalar: 0xF256F)
    public static let pauseFill = HugeIcon(name: "pause", scalar: 0xF22D7)
    public static let pencil = HugeIcon(name: "edit-02", scalar: 0xF1C02)
    public static let percent = HugeIcon(name: "percent-circle", scalar: 0xF22F8)
    public static let person = HugeIcon(name: "user", scalar: 0xF2949)
    public static let person2 = HugeIcon(name: "user-multiple", scalar: 0xF292E)
    public static let personBadgeMinus = HugeIcon(name: "user-minus-01", scalar: 0xF292A)
    public static let personBadgePlus = HugeIcon(name: "user-add-01", scalar: 0xF2914)
    public static let personCircle = HugeIcon(name: "user-circle", scalar: 0xF291D)
    public static let personCircleFill = HugeIcon(name: "user-circle", scalar: 0xF291D)
    public static let personCropCircleBadgePlus = HugeIcon(name: "user-add-01", scalar: 0xF2914)
    public static let personCropCircleFill = HugeIcon(name: "user-circle", scalar: 0xF291D)
    public static let personTextRectangle = HugeIcon(name: "contact-01", scalar: 0xF1A66)
    public static let photo = HugeIcon(name: "image-01", scalar: 0xF1E85)
    public static let photoArtframe = HugeIcon(name: "image-composition", scalar: 0xF1E8C)
    public static let photoBadgePlus = HugeIcon(name: "image-add-01", scalar: 0xF1E89)
    public static let photoOnRectangle = HugeIcon(name: "image-02", scalar: 0xF1E86)
    public static let playFill = HugeIcon(name: "play", scalar: 0xF2348)
    public static let plus = HugeIcon(name: "add-01", scalar: 0xF150C)
    public static let plusCircle = HugeIcon(name: "add-circle", scalar: 0xF150F)
    public static let plusCircleFill = HugeIcon(name: "add-circle", scalar: 0xF150F)
    public static let qrcode = HugeIcon(name: "qr-code", scalar: 0xF23DC)
    public static let questionmarkCircle = HugeIcon(name: "help-circle", scalar: 0xF1E11)
    public static let rectanglePortraitAndArrowRight = HugeIcon(name: "logout-01", scalar: 0xF1FFB)
    public static let safari = HugeIcon(name: "compass", scalar: 0xF1A3C)
    public static let shield = HugeIcon(name: "security", scalar: 0xF2563)
    public static let shieldFill = HugeIcon(name: "security", scalar: 0xF2563)
    public static let sidebarLeft = HugeIcon(name: "sidebar-left", scalar: 0xF25F4)
    public static let sliderHorizontal3 = HugeIcon(name: "settings-02", scalar: 0xF2580)
    public static let sparkle = HugeIcon(name: "sparkles", scalar: 0xF266B)
    public static let sparkles = HugeIcon(name: "sparkles", scalar: 0xF266B)
    public static let square = HugeIcon(name: "square", scalar: 0xF26C5)
    public static let squareAndArrowDown = HugeIcon(name: "download-01", scalar: 0xF1BB4)
    public static let squareAndArrowUp = HugeIcon(name: "upload-01", scalar: 0xF28FB)
    public static let squareAndPencil = HugeIcon(name: "edit-02", scalar: 0xF1C02)
    public static let squareGrid2x2 = HugeIcon(name: "grid-view", scalar: 0xF1DB6)
    public static let star = HugeIcon(name: "star", scalar: 0xF26D7)
    public static let starFill = HugeIcon(name: "star", scalar: 0xF26D7)
    public static let swift = HugeIcon(name: "code", scalar: 0xF1A0E)
    public static let tag = HugeIcon(name: "tags", scalar: 0xF27A1)
    public static let takeoutbagAndCupAndStraw = HugeIcon(name: "chef", scalar: 0xF197C)
    public static let takeoutbagAndCupAndStrawFill = HugeIcon(name: "chef", scalar: 0xF197C)
    public static let terminal = HugeIcon(name: "computer-terminal-01", scalar: 0xF1A54)
    public static let textAlignleft = HugeIcon(name: "text-align-left", scalar: 0xF27E5)
    public static let textBubble = HugeIcon(name: "message-01", scalar: 0xF20E9)
    public static let timer = HugeIcon(name: "timer-01", scalar: 0xF284E)
    public static let trash = HugeIcon(name: "delete-02", scalar: 0xF1B35)
    public static let wandAndStars = HugeIcon(name: "ai-magic", scalar: 0xF154A)
    public static let xmark = HugeIcon(name: "cancel-01", scalar: 0xF18BC)
    public static let xmarkCircle = HugeIcon(name: "cancel-circle", scalar: 0xF18BF)
    public static let xmarkCircleFill = HugeIcon(name: "cancel-circle", scalar: 0xF18BF)

    public static let allCases: [HugeIcon] = [
        .alarmFill,
        .appleLogo,
        .arrowClockwise,
        .arrowCounterclockwise,
        .arrowDown,
        .arrowLeft,
        .arrowLeftArrowRight,
        .arrowRight,
        .arrowTriangle2Circlepath,
        .arrowTurnDownRight,
        .arrowUp,
        .arrowUpArrowDown,
        .arrowUpForwardApp,
        .arrowUpRight,
        .barcode,
        .barcodeViewfinder,
        .bell,
        .bellBadgeFill,
        .bellFill,
        .bolt,
        .boltFill,
        .bookClosed,
        .bookClosedFill,
        .bookFill,
        .bookmark,
        .bookmarkFill,
        .booksVertical,
        .cabinet,
        .calendar,
        .calendarBadgeMinus,
        .calendarBadgePlus,
        .camera,
        .cameraFill,
        .cameraViewfinder,
        .carrot,
        .cart,
        .cartBadgePlus,
        .cartFill,
        .characterBubble,
        .chartBar,
        .checklistChecked,
        .checklistUnchecked,
        .checkmark,
        .checkmarkCircle,
        .checkmarkCircleFill,
        .checkmarkSealFill,
        .checkmarkSquare,
        .checkmarkSquareFill,
        .chevronDown,
        .chevronLeft,
        .chevronRight,
        .chevronUpChevronDown,
        .circle,
        .circleDashed,
        .clock,
        .clockArrowCirclepath,
        .creditcard,
        .creditcardFill,
        .cursorarrowClick2,
        .deleteBackward,
        .dialMedium,
        .docOnClipboard,
        .docOnDoc,
        .docText,
        .dollarsignCircle,
        .ellipsis,
        .ellipsisCircle,
        .envelope,
        .envelopeFill,
        .exclamationmark,
        .exclamationmarkBubble,
        .exclamationmarkTriangleFill,
        .flame,
        .flameFill,
        .flashlightOffFill,
        .flashlightOnFill,
        .folderBadgePlus,
        .forkKnife,
        .gearshape,
        .gearshape2,
        .globe,
        .heart,
        .heartFill,
        .house,
        .infoCircle,
        .infoCircleFill,
        .internaldrive,
        .key,
        .line3Horizontal,
        .line3HorizontalDecrease,
        .line3HorizontalDecreaseCircle,
        .link,
        .listBullet,
        .listNumber,
        .lock,
        .lockFill,
        .magnifyingglass,
        .mic,
        .micFill,
        .minus,
        .paintpalette,
        .paintpaletteFill,
        .paperplane,
        .pauseFill,
        .pencil,
        .percent,
        .person,
        .person2,
        .personBadgeMinus,
        .personBadgePlus,
        .personCircle,
        .personCircleFill,
        .personCropCircleBadgePlus,
        .personCropCircleFill,
        .personTextRectangle,
        .photo,
        .photoArtframe,
        .photoBadgePlus,
        .photoOnRectangle,
        .playFill,
        .plus,
        .plusCircle,
        .plusCircleFill,
        .qrcode,
        .questionmarkCircle,
        .rectanglePortraitAndArrowRight,
        .safari,
        .shield,
        .shieldFill,
        .sidebarLeft,
        .sliderHorizontal3,
        .sparkle,
        .sparkles,
        .square,
        .squareAndArrowDown,
        .squareAndArrowUp,
        .squareAndPencil,
        .squareGrid2x2,
        .star,
        .starFill,
        .swift,
        .tag,
        .takeoutbagAndCupAndStraw,
        .takeoutbagAndCupAndStrawFill,
        .terminal,
        .textAlignleft,
        .textBubble,
        .timer,
        .trash,
        .wandAndStars,
        .xmark,
        .xmarkCircle,
        .xmarkCircleFill,
    ]

    static func legacy(_ name: String) -> HugeIcon? {
        switch name {
        case "alarm.fill": .alarmFill
        case "apple.logo": .appleLogo
        case "arrow.clockwise": .arrowClockwise
        case "arrow.counterclockwise": .arrowCounterclockwise
        case "arrow.down": .arrowDown
        case "arrow.left": .arrowLeft
        case "arrow.left.arrow.right": .arrowLeftArrowRight
        case "arrow.right": .arrowRight
        case "arrow.triangle.2.circlepath": .arrowTriangle2Circlepath
        case "arrow.turn.down.right": .arrowTurnDownRight
        case "arrow.up": .arrowUp
        case "arrow.up.arrow.down": .arrowUpArrowDown
        case "arrow.up.forward.app": .arrowUpForwardApp
        case "arrow.up.right": .arrowUpRight
        case "barcode": .barcode
        case "barcode.viewfinder": .barcodeViewfinder
        case "bell": .bell
        case "bell.badge.fill": .bellBadgeFill
        case "bell.fill": .bellFill
        case "bolt": .bolt
        case "bolt.fill": .boltFill
        case "book.closed": .bookClosed
        case "book.closed.fill": .bookClosedFill
        case "book.fill": .bookFill
        case "bookmark": .bookmark
        case "bookmark.fill": .bookmarkFill
        case "books.vertical": .booksVertical
        case "cabinet": .cabinet
        case "calendar": .calendar
        case "calendar.badge.minus": .calendarBadgeMinus
        case "calendar.badge.plus": .calendarBadgePlus
        case "camera": .camera
        case "camera.fill": .cameraFill
        case "camera.viewfinder": .cameraViewfinder
        case "carrot": .carrot
        case "cart": .cart
        case "cart.badge.plus": .cartBadgePlus
        case "cart.fill": .cartFill
        case "character.bubble": .characterBubble
        case "chart.bar": .chartBar
        case "checklist.checked": .checklistChecked
        case "checklist.unchecked": .checklistUnchecked
        case "checkmark": .checkmark
        case "checkmark.circle": .checkmarkCircle
        case "checkmark.circle.fill": .checkmarkCircleFill
        case "checkmark.seal.fill": .checkmarkSealFill
        case "checkmark.square": .checkmarkSquare
        case "checkmark.square.fill": .checkmarkSquareFill
        case "chevron.down": .chevronDown
        case "chevron.left": .chevronLeft
        case "chevron.right": .chevronRight
        case "chevron.up.chevron.down": .chevronUpChevronDown
        case "circle": .circle
        case "circle.dashed": .circleDashed
        case "clock": .clock
        case "clock.arrow.circlepath": .clockArrowCirclepath
        case "creditcard": .creditcard
        case "creditcard.fill": .creditcardFill
        case "cursorarrow.click.2": .cursorarrowClick2
        case "delete.backward": .deleteBackward
        case "dial.medium": .dialMedium
        case "doc.on.clipboard": .docOnClipboard
        case "doc.on.doc": .docOnDoc
        case "doc.text": .docText
        case "dollarsign.circle": .dollarsignCircle
        case "ellipsis": .ellipsis
        case "ellipsis.circle": .ellipsisCircle
        case "envelope": .envelope
        case "envelope.fill": .envelopeFill
        case "exclamationmark": .exclamationmark
        case "exclamationmark.bubble": .exclamationmarkBubble
        case "exclamationmark.triangle.fill": .exclamationmarkTriangleFill
        case "flame": .flame
        case "flame.fill": .flameFill
        case "flashlight.off.fill": .flashlightOffFill
        case "flashlight.on.fill": .flashlightOnFill
        case "folder.badge.plus": .folderBadgePlus
        case "fork.knife": .forkKnife
        case "gearshape": .gearshape
        case "gearshape.2": .gearshape2
        case "globe": .globe
        case "heart": .heart
        case "heart.fill": .heartFill
        case "house": .house
        case "info.circle": .infoCircle
        case "info.circle.fill": .infoCircleFill
        case "internaldrive": .internaldrive
        case "key": .key
        case "line.3.horizontal": .line3Horizontal
        case "line.3.horizontal.decrease": .line3HorizontalDecrease
        case "line.3.horizontal.decrease.circle": .line3HorizontalDecreaseCircle
        case "link": .link
        case "list.bullet": .listBullet
        case "list.number": .listNumber
        case "lock": .lock
        case "lock.fill": .lockFill
        case "magnifyingglass": .magnifyingglass
        case "mic": .mic
        case "mic.fill": .micFill
        case "minus": .minus
        case "paintpalette": .paintpalette
        case "paintpalette.fill": .paintpaletteFill
        case "paperplane": .paperplane
        case "pause.fill": .pauseFill
        case "pencil": .pencil
        case "percent": .percent
        case "person": .person
        case "person.2": .person2
        case "person.badge.minus": .personBadgeMinus
        case "person.badge.plus": .personBadgePlus
        case "person.circle": .personCircle
        case "person.circle.fill": .personCircleFill
        case "person.crop.circle.badge.plus": .personCropCircleBadgePlus
        case "person.crop.circle.fill": .personCropCircleFill
        case "person.text.rectangle": .personTextRectangle
        case "photo": .photo
        case "photo.artframe": .photoArtframe
        case "photo.badge.plus": .photoBadgePlus
        case "photo.on.rectangle": .photoOnRectangle
        case "play.fill": .playFill
        case "plus": .plus
        case "plus.circle": .plusCircle
        case "plus.circle.fill": .plusCircleFill
        case "qrcode": .qrcode
        case "questionmark.circle": .questionmarkCircle
        case "rectangle.portrait.and.arrow.right": .rectanglePortraitAndArrowRight
        case "safari": .safari
        case "shield": .shield
        case "shield.fill": .shieldFill
        case "sidebar.left": .sidebarLeft
        case "slider.horizontal.3": .sliderHorizontal3
        case "sparkle": .sparkle
        case "sparkles": .sparkles
        case "square": .square
        case "square.and.arrow.down": .squareAndArrowDown
        case "square.and.arrow.up": .squareAndArrowUp
        case "square.and.pencil": .squareAndPencil
        case "square.grid.2x2": .squareGrid2x2
        case "star": .star
        case "star.fill": .starFill
        case "swift": .swift
        case "tag": .tag
        case "takeoutbag.and.cup.and.straw": .takeoutbagAndCupAndStraw
        case "takeoutbag.and.cup.and.straw.fill": .takeoutbagAndCupAndStrawFill
        case "terminal": .terminal
        case "text.alignleft": .textAlignleft
        case "text.bubble": .textBubble
        case "timer": .timer
        case "trash": .trash
        case "wand.and.stars": .wandAndStars
        case "xmark": .xmark
        case "xmark.circle": .xmarkCircle
        case "xmark.circle.fill": .xmarkCircleFill
        default: nil
        }
    }
}
