#!/usr/bin/env python3
"""Generate ZenKit's type-safe HugeIcons catalog and subset font."""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import subprocess
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
MANIFEST = ROOT / "Sources/ZenKit/Icons/hugeicons-manifest.json"
OUTPUT_SWIFT = ROOT / "Sources/ZenKit/Icons/HugeIcon.generated.swift"
OUTPUT_FONT = ROOT / "Sources/ZenKit/Icons/Resources/HugeiconsStrokeRounded.subset.ttf"


def sha256(path: Path) -> str:
    return hashlib.sha256(path.read_bytes()).hexdigest()


def swift_name(sf_name: str) -> str:
    chunks = re.split(r"[^A-Za-z0-9]+", sf_name)
    return chunks[0] + "".join(chunk[:1].upper() + chunk[1:] for chunk in chunks[1:])


def parse_css(css: str) -> dict[str, int]:
    pattern = re.compile(
        r"\.hgi-stroke\.hgi-([a-z0-9-]+)::before\s*\{\s*content:\s*\"\\([0-9a-fA-F]+)\";",
        re.MULTILINE,
    )
    return {name: int(codepoint, 16) for name, codepoint in pattern.findall(css)}


def generate_swift(font_family: str, icons: dict[str, str], codepoints: dict[str, int]) -> str:
    declarations: list[str] = []
    all_cases: list[str] = []
    legacy_lookup: list[str] = []
    for sf_name, huge_name in sorted(icons.items()):
        case_name = swift_name(sf_name)
        codepoint = codepoints[huge_name]
        declarations.append(
            f'    public static let {case_name} = HugeIcon(name: "{huge_name}", scalar: 0x{codepoint:X})'
        )
        all_cases.append(f"        .{case_name},")
        legacy_lookup.append(f'        case "{sf_name}": .{case_name}')

    return f'''// Generated by Scripts/update_hugeicons.py. Do not edit.
import Foundation

public struct HugeIcon: Hashable, Sendable, Identifiable {{
    public let name: String
    public let scalar: UInt32

    public var id: String {{ name }}

    public var character: String {{
        UnicodeScalar(scalar).map(String.init) ?? ""
    }}

    private init(name: String, scalar: UInt32) {{
        self.name = name
        self.scalar = scalar
    }}

    public static let fontFamily = "{font_family}"

{chr(10).join(declarations)}

    public static let allCases: [HugeIcon] = [
{chr(10).join(all_cases)}
    ]

    static func legacy(_ name: String) -> HugeIcon? {{
        switch name {{
{chr(10).join(legacy_lookup)}
        default: nil
        }}
    }}
}}
'''


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--css", type=Path, required=True)
    parser.add_argument("--font", type=Path, required=True)
    parser.add_argument("--fonttools-path", type=Path)
    args = parser.parse_args()

    manifest = json.loads(MANIFEST.read_text())
    if sha256(args.css) != manifest["source"]["cssSHA256"]:
        raise SystemExit("CSS SHA-256 does not match hugeicons-manifest.json")
    if sha256(args.font) != manifest["source"]["fontSHA256"]:
        raise SystemExit("Font SHA-256 does not match hugeicons-manifest.json")

    codepoints = parse_css(args.css.read_text())
    icons: dict[str, str] = manifest["icons"]
    missing = sorted(set(icons.values()) - set(codepoints))
    if missing:
        raise SystemExit(f"Missing HugeIcons classes in CSS: {', '.join(missing)}")

    OUTPUT_SWIFT.write_text(generate_swift(manifest["fontFamily"], icons, codepoints))
    unicodes = ",".join(f"U+{codepoints[name]:X}" for name in sorted(set(icons.values())))
    environment = None
    if args.fonttools_path:
        environment = dict(__import__("os").environ)
        environment["PYTHONPATH"] = str(args.fonttools_path)
    subprocess.run(
        [
            sys.executable,
            "-m",
            "fontTools.subset",
            str(args.font),
            f"--output-file={OUTPUT_FONT}",
            f"--unicodes={unicodes}",
            "--glyph-names",
            "--symbol-cmap",
            "--legacy-cmap",
            "--notdef-glyph",
            "--notdef-outline",
            "--recommended-glyphs",
            "--name-IDs=*",
            "--name-legacy",
            "--name-languages=*",
        ],
        check=True,
        env=environment,
    )
    print(f"Generated {len(icons)} semantic icons from {len(set(icons.values()))} glyphs")
    print(f"Subset font: {OUTPUT_FONT.stat().st_size} bytes")


if __name__ == "__main__":
    main()
