enum ShowcaseScreenID: String, Equatable {
    // Foundations
    case theme
    // Inputs
    case buttons
    case login
    case textInput
    case toggle
    case segmentedControl
    case pickerRow
    case multiSelect
    case selectCard
    case stepper
    case searchBar
    case tagInput
    case datePicker
    case label
    case radioGroup
    case sensitiveInput
    case inputGroup
    case autocomplete
    case combobox
    // Feedback
    case spinner
    case statusBanner
    case skeleton
    case emptyState
    case alert
    case popover
    case tooltip
    // Navigation
    case navigationRow
    case menu
    case swipeRow
    case link
    case breadcrumbs
    case pagination
    case menubar
    case sidebar
    case commandPalette
    case tableOfContents
    // Surfaces
    case card
    case section
    case field
    case settings
    case disclosure
    case sheet
    case layerCard
    case grid
    // Data Display
    case badge
    case progressBar
    case avatar
    case metrics
    case rating
    case pageIndicator
    case colorSwatch
    case timeline
    case buttonLabel
    case text
    case meter
    case clipboardText
    case codeBlock
    case table
}
